### ISSUE TITLE
Return more information and highlights on keyword searches

### ISSUE THREAD

**Issue by reckart** [pubannotation/pubannotation#5]
Keyword query should return additional information:

- at least the same information also shown in the HTML result
- text snippets with match highlights 
- match score
- timestamp of the document

**Comment by reckart** [comment]
@jdkim do you have some test server where I can test against your changes?

**Comment by jdkim** [comment]
@reckart we gave it a try but failed to deploy it in production mode. we will give it another try tomorrow.

**Comment by reckart** [comment]
Ok. I could meanwhile also test against a non-production server since I made the PubAnnotation URL setting in INCEpTION configurable ;)

**Comment by jdkim** [comment]
It's just done. Try this test service:
http://pubannotation-test.dbcls.jp/

**Comment by jdkim** [comment]
The requested feature for text snippets with match highlights is deployed.

**Comment by reckart** [comment]
Thanks. Will test asap and report back.

**Comment by reckart** [comment]
Looks quite nice with the highlights :)

The matching algorithm of the PubAnnotation search backend looks a bit strange. E.g. when searching for "offering", it returns highlights for "afferent" (see screenshot).


<img width="1052" alt="2019-02-25_22-29-53" src="https://user-images.githubusercontent.com/1410238/53370043-eb549f00-394c-11e9-904d-896f106fcc63.png">

Would it be possible to also include a score in the JSON results?

Given that PubAnnotation focusses on scientific publications, it would be nice to have some support for document-level metadata such as title, authors, publication year, etc. But that could go into another issue.
