### ISSUE TITLE
Paging not supported for JSON results

### ISSUE THREAD

**Issue by reckart** [pubannotation/pubannotation#6]
For HTML results, paging seems to be supported everywhere, e.g.

- Browsing: http://pubannotation.org/docs/sourcedb/PMC?page=4
- Searching: http://pubannotation.org/docs/sourcedb/PMC?keywords=offering&page=2&utf8=✓

But not in JSON mode:

- http://pubannotation.org/docs/sourcedb/PMC.json?keywords=offering&page=2&utf8=✓

**Comment by jdkim** [comment]
Closed for preference to addressing #7
